### ISSUE TITLE
VT API Key

### ISSUE THREAD

**Issue by alexander-hanel** [vapaspen/Libraries#1]
Your private VT API key is present in `Libraries/VT/VTConfig.py`. You might want to remove your key and ask VT to generate a new one.

**Comment by vapaspen** [comment]
Thank you for pointing this out. I when out of my way to protect my company key, but didn't even thing about that one. I did want to know how out found this repo? Was it a good search related to something I am making? Or some other way? 

I ask because I am reworking all of this to be more generally usable and I would gladly offer my rework, or what parts of it you are looking for.

**Comment by alexander-hanel** [comment]
Accidents happen. I found your code by searching for the string `virustotal.com/intelligence`. I  was looking for example code that would allow me to download files via a search query. VT already has the capability in their vt_intelligence downloader.py. I want to do it via a function call rather than the command line. Odds are I can hack their code into something ;)

**Comment by vapaspen** [comment]
Its just a POST call to a Rest API. These are the 2 URLs you send the call to, First is the Search, second is the download. The Download only takes hashes, but it will take md5, sha1 and sha256. 
The search needs post data of: {'query': <str>, 'apikey': <str>, 'page': <str>} If you do not provide a page key you will get the first Page. 
'https://www.virustotal.com/intelligence/search/programmatic/'
'https://www.virustotal.com/intelligence/download/?hash=%s&apikey=%s'
